### ISSUE TITLE
[Feature Request]: Ability to sync roles in single transaction

### ISSUE THREAD

**Issue by mdsadiqueinam** [holoyan/adonisjs-permissions#10]
Add the ability to sync roles(assignAllRoles, forbidAllRoles together) in single transaction so that if anything goes wrong it will fallback to its original state

**Comment by holoyan** [comment]
Hi @mdsadique-inam,

Thanks for the request, it will be a nice addition, will add

**Comment by mdsadique-inam** [comment]
Hi @holoyan 👋 
Also it will be great to have an optional parameter to pass the transaction instance like TransactionContract making it a part of different functions

**Comment by holoyan** [comment]
Hi @mdsadique-inam 

[Transaction](https://github.com/holoyan/adonisjs-permissions?tab=readme-ov-file#transactions) support added
