### ISSUE TITLE
I encountered some errors despite following your documentation, such as these errors.

### ISSUE THREAD

**Issue by MrAhmedElkady** [holoyan/adonisjs-permissions#12]
![image](https://github.com/holoyan/adonisjs-permissions/assets/53810738/301e33ce-f1e7-45cf-b238-58fe3626bae8)

When adding true to AclManager, this issue disappears, but I can't utilize any of the library's features, as shown in the following image.
![image](https://github.com/holoyan/adonisjs-permissions/assets/53810738/bcdefe44-3263-4ac1-a0a3-2fb4d4bc1df4)

**Comment by holoyan** [comment]
Hi @MrAhmedElkady 

Seems that you forget to use `await`

```typescript

const user  = await User.first()

```

let me know  if it fixes the issue

**Comment by MrAhmedElkady** [comment]
Yes, it is now working, but another error appears as shown in the picture... What is the reason for that?
![image](https://github.com/holoyan/adonisjs-permissions/assets/53810738/ba1e6695-7e7b-41ee-942c-508f3a3ca4cb)

**Comment by holoyan** [comment]
@MrAhmedElkady can you copy past the code here?

 middleware handle method, routing line and the controller method

**Comment by MrAhmedElkady** [comment]
As you can see, I was trying to create a sample code to test if the library works and if it meets the requirements.
user model:
`import { DateTime } from 'luxon'
import hash from '@adonisjs/core/services/hash'
import { compose } from '@adonisjs/core/helpers'
import { BaseModel, column } from '@adonisjs/lucid/orm'
import { withAuthFinder } from '@adonisjs/auth/mixins/lucid'
import { AclModelInterface } from '@holoyan/adonisjs-permissions/types'
import { hasPermissions } from '@holoyan/adonisjs-permissions'
import { MorphMap } from '@holoyan/adonisjs-permissions'

const AuthFinder = withAuthFinder(() => hash.use('scrypt'), {
  uids: ['email'],
  passwordColumnName: 'password',
})

@MorphMap('users')
export default class User extends compose(BaseModel, hasPermissions(), AuthFinder) implements AclModelInterface {
  getModelId(): number {
    return this.id
  }

  @column({ isPrimary: true })
  declare id: number

  @column()
  declare fullName: string | null

  @column()
  declare email: string

  @column({ serializeAs: null })
  declare password: string

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null


}`
middleware:
`import type { HttpContext } from '@adonisjs/core/http'
import type { NextFn } from '@adonisjs/core/types/http'
import { AclManager, Scope } from '@holoyan/adonisjs-permissions'

declare module '@adonisjs/core/http' {
  export interface HttpContext {
    acl: AclManager
  }
}

export default class UserScopeMiddleware {
  //@ts-ignore
  async handle(ctx: HttpContext, next: NextFn) {
    const scope = new Scope()
    ctx.acl = new AclManager(true).scope(scope)
    /**
     * Call next method in the pipeline and return its output
     */
    const output = await next()
    return output
  }
}`

route:
`router.group(() => {
    router.get('AddRole', [UsersController, 'create']).as("testRole")
})`

controlller:
`  async create({ acl }: HttpContext) {

    const user = await User.first()
    if (user) {
      // acl from the {acl}: HttpContext
      await acl.model(user).assignRole('admin')
    }
    return user
  }`

**Comment by holoyan** [comment]
Hi @MrAhmedElkady ,

thanks you for youe support, just pushed new verions https://github.com/holoyan/adonisjs-permissions/pull/13 , please update to version `v0.8.18` and try again. Let me know if it works for you
