### ISSUE TITLE
The scope is not changing when assigning permission to scope with `on` method

### ISSUE THREAD

**Issue by mdsadique-inam** [holoyan/adonisjs-permissions#9]
I an trying to assign roles to permission using 
```ts
await Acl.role(role).on('group').assingAll(permissions, Model)
```
and every time it creates new permission with scope 'default'

**Comment by holoyan** [comment]
Hi @mdsadique-inam ,

I see the issue, will push fix today

**Comment by holoyan** [comment]
Hi @mdsadique-inam, 

I see the issue,

just pushed the [fix](https://github.com/holoyan/adonisjs-permissions/commit/84f94127d91054657f6fe83fa8f48ccb53d883eb), typo fixed as well (method renamed from assingAll -> assignAll)

please let me know if it fixed.

**Comment by mdsadique-inam** [comment]
Hi @holoyan :wave: 
Now it is working

**Comment by holoyan** [comment]
Nice, 

Thank you for your support
